#!/bin/bash

POkEMON_LIST=("bulbasaur" "ivysaur" "venusaur" "charmander" "charmeleon")
OUTPUT_DIR="Advanced_shell"

for pokemon in "${POkEMON_LIST[@]}"; do
    API_URL="https://pokeapi.co/api/v2/pokemon/$pokemon"
    echo "Fetching data for $pokemon ..."
    
    status_code=$(curl -s -w "%{http_code}" "$API_URL" -o "$OUTPUT_DIR/$pokemon.json")

    if [ "$status_code" -eq 200 ]; then
        echo "Successfully fetched data for $pokemon"
    else
        echo "Failed to fetch data for $pokemon. Status code: $status_code"
    fi

    sleep 1  # Pause for 1 second between requests
done
