#!/bin/bash

POkEMON_LIST=("bulbasaur" "ivysaur" "venusaur" "charmander" "charmeleon")
INPUT_DIR="Advanced_shell"
OUTPUT_FILE="Advanced_shell/pokemon_report.csv"

:> "$OUTPUT_FILE"  # Clear previous output file
echo "Name, Height (m), Weight (kg)" >> "$OUTPUT_FILE"

for pokemon in "${POkEMON_LIST[@]}"; do
    file="$INPUT_DIR/$pokemon.json"

    if [ ! -f "$file" ]; then
        echo "File $file does not exist. Skipping."
        continue
    fi

    name=$(jq -r '.name' "$file" | sed 's/.*/\u&/')
    height=$(jq -r '.height' "$file")
    weight=$(jq -r '.weight' "$file")
    formatted_height=$(awk -v h="$height" 'BEGIN {printf "%.1f", h/10}')
    formatted_weight=$(awk -v w="$weight" 'BEGIN {printf "%.f", w/10}')

    echo "$name, $formatted_height, $formatted_weight" >> "$OUTPUT_FILE"
    echo "Processing $pokemon completed."
    sleep 1
done

cat "$OUTPUT_FILE"
echo ""

# Calculate averages

awk -F, 'NR>1 {sum_height+=$2; sum_weight+=$3; count++} END {if (count > 0) {printf "Average Height: %.2fm\nAverage Weight: %.fkg\n", sum_height/count, sum_weight/count} else {print "No data to calculate averages."}}' "$OUTPUT_FILE"
